WIP: Add /showinfo
LabsDevelopment/Boyfriend pull request #122
Opened 2023-09-27 22:00 UTC by mctaylors

2023-09-28 10:18 UTC, Octol1ttle requested changes

2023-09-28 10:18 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Display Name</value>
```suggestion
        <value>Display name</value>
```

2023-09-28 10:18 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +        <value>Заглушен с помощью мут роли</value>
```suggestion
        <value>Заглушен с помощью мут-роли</value>
```
or
```suggestion
        <value>Заглушен с помощью роли мута</value>
```

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +
xmldocs

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +
xmldocs

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        [Description("Specific user or ID to show info about")]
needs to be less verbose

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        return await ShowUserInfoAsync(user, currentUser, data, guildId, CancellationToken);
```suggestion
        return await ShowUserInfoAsync(target ?? user, currentUser, data, guildId, CancellationToken);
```

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        guildMemberResult.IsDefined(out var guildMember);
result of method call is not used. either use `.Entity` or use the boolean returned

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        var isMuted = (memberData.MutedUntil is not null && DateTimeOffset.UtcNow <= memberData.MutedUntil) ||
`MemberData#MutedUntil` will always be null if `DateTimeOffset#UtcNow > MemberData#MutedUntil` +- 1 member data tick

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        var existingBanResult = await _guildApi.GetGuildBanAsync(guildId, user.ID, ct);
Variable declared far before its first usage

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +            builder.Append("- ").AppendLine(Messages.ShowInfoBannedPermanently);
Because these conditions are mutually exclusive, you can simply return early instead of using another `if` block

2023-09-28 10:18 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        if (guildMember is not null && guildMember.CommunicationDisabledUntil.IsDefined())
Combinations of `IsDefined()` and `.Value`/`.Entity` should always be replaced with `IsDefined(out var value)`

2023-09-28 13:00 UTC, mctaylors commented on src/Commands/ToolsCommandGroup.cs
> +        var isMuted = (memberData.MutedUntil is not null && DateTimeOffset.UtcNow <= memberData.MutedUntil) ||
`MemberData#MutedUntil` will not be null if user left the server while role-muted

2023-09-28 15:33 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    ///     A slash command that shows information about user.
Please specify exactly the information shown

2023-09-28 15:33 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    private static void ShowInfoBannedUntilAsync(MemberData memberData, StringBuilder builder)
rename to something like `AppendBanInformation`

2023-09-28 16:24 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    ///     A slash command that shows general information about user & user's punishments.
*sigh* I want an exhaustive list.

2023-09-28 19:16 UTC, Octol1ttle requested changes

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.resx
> +    <data name="NotPresent" xml:space="preserve">
Unused translation

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.resx
> +    <data name="ShowInfoMentionedAs" xml:space="preserve">
Unused translation

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.resx
> +    <data name="ShowInfoNotOnServer" xml:space="preserve">
In English, Discord servers are usually referred to as guilds

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Muted with a mute role</value>
```suggestion
        <value>Muted by timeout</value>
    </data>
    <data name="ShowInfoMutedWithMuteRole" xml:space="preserve">
        <value>Muted by mute role</value>
```

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Guild Nitro booster since</value>
```suggestion
        <value>Nitro booster since</value>
```

2023-09-28 19:16 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +        <value>Пользователь Discord с</value>
```suggestion
        <value>Вступил в Discord</value>
```

2023-09-28 19:32 UTC, mctaylors commented on locale/Messages.ru.resx
> +        <value>Участник сервера с</value>
it would be more correct to "вступил на сервер"

2023-09-28 19:40 UTC, mctaylors commented on src/Commands/ToolsCommandGroup.cs
> +    ///     and current punishments.
explained in Discord

2023-09-28 19:40 UTC, mctaylors commented on src/Commands/ToolsCommandGroup.cs
> +                .Append(" - ").AppendLine(string.Format(
explained in Discord

2023-09-28 20:00 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    ///     Information on the output:
```suggestion
    ///     Information in the output:
```

2023-09-28 20:00 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Not on the guild</value>
```suggestion
        <value>Not in the guild</value>
```

2023-09-29 11:20 UTC, Octol1ttle approved these changes

2023-09-29 12:31 UTC, merged