WIP: Redesign embeds
LabsDevelopment/Boyfriend pull request #123
Opened 2023-09-27 22:03 UTC by mctaylors

Blocked by #122

2023-09-28 10:22 UTC, Octol1ttle requested changes

2023-09-28 10:22 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Boyfriend's Repository</value>
it might be confusing what a `Repository` is to people who aren't used to terminology

2023-09-28 10:22 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +        <value>Открыть сообщение: {0}</value>
```suggestion
        <value>Перейти к сообщению: {0}</value>
```

2023-09-28 10:22 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +        new() { 504343489664909322, 326642240229474304, 474943797063843851 };
1) Why is a List necessary?
2) Use tuples instead

2023-09-28 10:22 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +        builder.Append("### [").Append(Messages.AboutTitleRepository)
ever heard of string interpolation?

2023-09-28 15:43 UTC, Octol1ttle commented on src/Extensions.cs
> +    // ReSharper disable once UnusedMember.Global
ayo?

2023-09-28 15:46 UTC, mctaylors commented on src/Extensions.cs
> +    // ReSharper disable once UnusedMember.Global
almost forgot about it

I thought I would use this method later

2023-09-28 15:56 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +        for (var i = 0; i < Developers.Length; i++)
Convert to `foreach`

2023-09-28 16:09 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>OK, I'll remind you about that</value>
@Apceniy a more natural-sounding translation is needed

2023-09-28 16:09 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +        <value>Хорошо, я напомню тебе об этом</value>
```suggestion
        <value>Хорошо, я тебе об этом напомню</value>
```

2023-09-28 16:14 UTC, Octol1ttle commented on locale/Messages.resx
> +    <data name="ReminderSentOn" xml:space="preserve">
misleading name - the translation key implies that the reminder already *was sent*

2023-09-28 19:00 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Reminder will be sent on: {0}</value>
```suggestion
        <value>The reminder will be sent on: {0}</value>
```

2023-09-29 11:22 UTC, Octol1ttle requested changes

2023-09-29 11:22 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Ok, {0}, I'll remind you that</value>
undo please

2023-09-29 11:22 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +        <value>Хорошо, {0}, я напомню тебе об этом</value>
^

2023-09-29 11:22 UTC, Octol1ttle commented on locale/Messages.tt-ru.resx
> +        <value>без проблем, {0}, напоминалка уже ждет</value>
^

2023-09-29 11:37 UTC, mctaylors commented on locale/Messages.resx
> +        <value>Ok, {0}, I'll remind you that</value>
elaborate

2023-09-29 11:50 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Ok, {0}, I'll remind you that</value>
```suggestion
        <value>Reminder for {0} created</value>
```

2023-09-29 12:01 UTC, mctaylors commented on locale/Messages.resx
> +        <value>Ok, {0}, I'll remind you that</value>
good job of killing "alive" user interaction

2023-09-29 12:05 UTC, Octol1ttle commented on locale/Messages.resx
> +        <value>Ok, {0}, I'll remind you that</value>
what was already there didn't sound natural at all

2023-09-29 13:26 UTC, Octol1ttle requested changes

2023-09-29 13:26 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +    private static readonly (string Username, ulong Id)[] Developers =
actually, you can store Snowflakes directly here instead of converting from ulongs each time the command is called

2023-09-29 13:26 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +            }
```suggestion
            var guildMemberResult = await _guildApi.GetGuildMemberAsync(
                guildId, dev.Id.ToSnowflake(), ct);
            var tag = guildMemberResult.IsSuccess ? $"<@{dev.Id}>" : $"@{dev.Username}";
```

2023-09-29 15:10 UTC, Octol1ttle requested changes
https://github.com/LabsDevelopment/Boyfriend/pull/123#discussion_r1341362454

2023-09-29 15:12 UTC, mctaylors commented
> [#123 (comment)](https://github.com/LabsDevelopment/Boyfriend/pull/123#discussion_r1341362454)

https://github.com/LabsDevelopment/Boyfriend/pull/123/commits/0e00069b9dd017b80556d79ab62533b35c35b620

2023-09-29 15:32 UTC, Octol1ttle approved these changes

2023-09-29 15:36 UTC, merged

2023-10-01 07:22 UTC, Apceniy commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
welcome back

2023-10-01 07:24 UTC, mctaylors commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
too late, sadly

2023-10-01 07:25 UTC, Apceniy commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
why does it matter

2023-10-01 07:28 UTC, mctaylors commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
I can't commit any new changes since PR was merged, _if I understand what the conversation is about now_.

You may refer this in a new issue.

2023-10-01 07:31 UTC, Apceniy commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
I didn't ask for new changes, I just reacted to the existing change

2023-10-01 07:32 UTC, mctaylors commented on locale/Messages.tt-ru.resx
> +        <value>напоминалка для {0} скрафченА</value>
Oh.